AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront and WAF Stack

Parameters:
  Project:
    Type: String
    Description: Project name to prefix resource names
  Environment:
    Type: String
    Description: Environment (e.g., dev, prod) to suffix resource names
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket to serve via CloudFront
  S3BucketDomainName:
    Type: String
    Description: Domain Name of the S3 bucket to serve
  S3LogsBucketArn:
    Type: String
    Description: Name of the S3 bucket to save CloudFront logs
  CloudFrontOAI:
    Type: String
    Description: The Origin Access Identity ID for the CloudFront distribution to access the S3 bucket

Resources:
  WebACL:
    Type: "AWS::WAFv2::WebACL"
    Properties:
      DefaultAction:
        Allow: {}
      Name: !Sub "${Project}-${Environment}-waf"
      Rules: []
      Scope: CLOUDFRONT
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "${Project}-${Environment}-metric-waf"
        SampledRequestsEnabled: true

  WebAppDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        CustomErrorResponses:
          - ErrorCachingMinTTL: 10
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
            AllowedMethods: ["GET", "HEAD"]
            CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6" # CachingOptimized id
            Compress: true
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Logging:
          Bucket: !Ref S3LogsBucketArn
        Origins:
          - DomainName: !Ref S3BucketDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        WebACLId: !GetAtt WebACL.Arn

Outputs:
  CloudFrontDomain:
    Description: CloudFront domain name
    Value: !GetAtt WebAppDistribution.DomainName
