AWSTemplateFormatVersion: '2010-09-09'
Description: LoanPro Chanllenge CloudFormation stack

Parameters:
  Project:
    Type: String
    Description: Project name to prefix resource names
    Default: "loanpro-challenge"

  Environment:
    Type: String
    Description: Environment (e.g., dev, prod) to suffix resource names
    Default: "dev"

  BucketUrl:
    Type: String
    Description: Bucket where the CloudFormation templates are going to be uploaded
    Default: "loanpro-challenge-iac-artifacts"

Resources:
  OriginAccessIdentityStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "${BucketUrl}/oai.yaml"

  S3BucketStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "${BucketUrl}/s3.yaml"
      Parameters:
        Project: !Ref Project
        Environment: !Ref Environment
        CloudFrontOAI: !GetAtt OriginAccessIdentityStack.Outputs.CloudFrontOAIId

  CloudFrontStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "${BucketUrl}/cloudfront.yaml"
      Parameters:
        Project: !Ref Project
        Environment: !Ref Environment
        S3BucketName: !GetAtt S3BucketStack.Outputs.FrontendBucketName
        S3BucketDomainName: !GetAtt S3BucketStack.Outputs.FrontendBucketDomainName
        S3LogsBucketDomainName: !GetAtt S3BucketStack.Outputs.LogsBucketDomainName
        CloudFrontOAI: !GetAtt OriginAccessIdentityStack.Outputs.CloudFrontOAIId

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket used to store the web app
    Value: !GetAtt S3BucketStack.Outputs.BucketName

  CloudFrontDomain:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDomain

  CloudFrontOAIId:
    Description: Origin Access Identity ID for CloudFront
    Value: !GetAtt OriginAccessIdentityStack.Outputs.CloudFrontOAIId

  WAFId:
    Description: ID of the Web Application Firewall associated with CloudFront
    Value: !GetAtt CloudFrontStack.Outputs.WebACLId
