AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront and WAF Stack

Parameters:
  Project:
    Type: String
    Description: Project name to prefix resource names
  Environment:
    Type: String
    Description: Environment (e.g., dev, prod) to suffix resource names
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket to serve via CloudFront
  S3LogsBucketName:
    Type: String
    Description: Name of the S3 bucket to save CloudFront logs
  CloudFrontOAIId:
    Type: String
    Description: The Origin Access Identity ID for the CloudFront distribution to access the S3 bucket

Resources:
  WebAppDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !Sub "${S3BucketName}.s3.amazonaws.com"
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAIId}"
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: ["GET", "HEAD"]
        Enabled: true
        WebACLId: !Ref WebACL
        Logging:
          Bucket: "cloudfront-logs-bucket-unique-name.s3.amazonaws.com"
        PriceClass: PriceClass_100
      ViewerCertificate:
        CloudFrontDefaultCertificate: true

  WebACL:
    Type: "AWS::WAFv2::WebACL"
    Properties:
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: "WebACL"
      Rules: []

Outputs:
  CloudFrontDomain:
    Description: CloudFront domain name
    Value: !GetAtt WebAppDistribution.DomainName
