AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB Table Stack

Parameters:
  Project:
    Type: String
    Description: Project name to prefix resource names

  Environment:
    Type: String
    Description: Environment (e.g., dev, prod) to suffix resource names

Resources:
  DynamoTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
        - AttributeName: "LSI"
          AttributeType: "N"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      LocalSecondaryIndexes:
        - IndexName: "LocalIndex"
          KeySchema:
            - AttributeName: "PK"
              KeyType: "HASH"
            - AttributeName: "LSI"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      SSESpecification:
        SSEEnabled: true
      TableName: !Sub "${Project}-${Environment}-table"

  TableLatencyAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "Alarm if 95th percentile latency of DynamoDB requests exceeds 400ms"
      AlarmName: !Sub "${Project}-${Environment}-dynamo-alarm"
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      Dimensions:
        - Name: "TableName"
          Value: !Ref DynamoTable
      ExtendedStatistic: "p95"  # 95% percentile
      MetricName: "SuccessfulRequestLatency"
      Namespace: "AWS/DynamoDB"
      Period: 3600  # Evaluation period in seconds
      EvaluationPeriods: 1
      Threshold: 400  # Threshold in milliseconds
      Unit: Milliseconds

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref DynamoTable
